language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
on:
  branch: master
deploy:
  provider: surge
  project: ./build/
  domain: team-cowgirl.surge.sh   
