language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
on:
  branch: master
deploy:
  provider: surge
  project: ./build
  domain: team-cowgirl.surge.sh   
  skip_cleanup: true
