name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install
        uses: bahmutov/npm-install@v1
      - name: Test
        run: npm test
        env:
          CI: true
      - name: Prepare version
        id: vars
        run: echo "version=$(date '+%Y%m%d%H%M%S')-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Build
        if: success()
        run:
          npm run build
        env:
          REACT_APP_GRAPHQL_ENDPOINT: "/graphql"
          REACT_APP_VERSION: ${{ steps.vars.outputs.version }}
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: production
          build_dir: build
          keep_history: true
          allow_empty_commit: false
          commit_message: "Production deploy"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          