name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install
        uses: bahmutov/npm-install@v1
      - name: Test
        run: npm test
        env:
          CI: true
      - name: Build
        if: success()
        run:
          npm run build
        env:
          REACT_APP_GRAPHQL_ENDPOINT: "/graphql"
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: production
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          